### ISSUE TITLE
Display order is not equal to order of IDs in list

### ISSUE THREAD

**Issue by I3undy** [Lombiq/Helpful-Extensions#1]
**dpomt** created on Apr 5, 2013: 
https://helpfulextensions.codeplex.com/workitem/2

I am using "Ids In filter" to list submenu items via a projection. 
I am expecting that the display order of the items in the projections is equal to the order with in the comma-separated id list, but it is not. 
A fix for this would be really helpful. Thanks!

**Comment by I3undy** [comment]
@Piedone commented on Jun 19, 2013:

Sorry not to reply earlier, I forgot to turn issue notifications on...

I'm not sure if this is possible (querying on the value of delegate is tricky with IHqlQuery) but will take a look at it.

**Comment by I3undy** [comment]
**dpomt** commented on Jan 17, 2014:

Just want to reuse "Ids in filter for another site and again remaining order would be good.
Any news on the Topic?
Thank you.

**Comment by I3undy** [comment]
@Piedone commented on Jan 17, 2014:

Nothing, sorry. There are two issues: this is not easy to do with HQL (but possible); the main problem is, however, that this is a filter provider and anything ordering-related should be handled from sort criteria.

**Comment by I3undy** [comment]
@Piedone commented on Mar 15, 2014:

I'm not even sure anymore whether this is possible: https://orchard.codeplex.com/discussions/538405

**Comment by I3undy** [comment]
@Piedone commented on May 6, 2014:

Unfortunately this seems not to be possible at the moment, the API doesn't allow it. There will be some changes in the Orchard data API in the next version so probably that will help.

**Comment by Piedone** [comment]
We won't do this anymore.
