### ISSUE TITLE
Was BootstrapAccordion removed? (OSOE-417)

### ISSUE THREAD

**Issue by devlife** [Lombiq/Helpful-Extensions#100]
I'm upgrading to OC 1.4 (from 1.2.1) and can no longer find `BootstrapAccordionItem`. Was this removed? 

https://github.com/Lombiq/Helpful-Extensions/commit/ff03017e6ad9ea8095e2a2007aaadcfd9fae3537

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-417)

**Comment by Piedone** [comment]
Yes, but it exists, it's now part of our UI Kit module: https://github.com/Lombiq/Orchard-UIKit/blob/dev/Lombiq.UIKit/Docs/BootstrapControls.md

**Comment by devlife** [comment]
Wonderful thank you!
