### ISSUE TITLE
Fix issues in target-blank.js (OSOE-576)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/Helpful-Extensions#116]
Follow-up to https://github.com/Lombiq/Helpful-Extensions/issues/104.

See comments [here](https://github.com/Lombiq/Helpful-Extensions/pull/114#pullrequestreview-1305260226) and below.

1. Use [`DOMContentLoaded`](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event) event instead of `load`. There's no third parameter there.
2. Remove the `setTimeout` indirection from the event handler. Simply pass `targetBlank` as the handler.
3. Remove superfluous configuration from package.json file:
   a. `"nodejsExtensions"`
   b. `"devDependencies"`
4. Use compiled scripts from _wwwroot\js_ folder instead of _wwwroot\scripts_ [here](https://github.com/Lombiq/Helpful-Extensions/blob/dev/Lombiq.HelpfulExtensions/ResourceManagementOptionsConfiguration.cs#L15) after 3.a.
5. Reorder the conditions [here](https://github.com/Lombiq/Helpful-Extensions/blob/dev/Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js#L7-L9).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-576)

**Comment by TheHydes** [comment]
From target-blank.js the whole second part can be removed starting with "window.addEventListener...", that makes the **"Use DOMContentLoaded event instead of..."** part unneccesary, right?

**Comment by 0liver** [comment]
No.

```js
    window.addEventListener(
        'load',
        () => {
            window.setTimeout(targetBlank, 100);
        },
        false);
```
Should become:
```js
    document.addEventListener('DOMContentLoaded', targetBlank);
```

**Comment by TheHydes** [comment]
I see, understood.

**Comment by Piedone** [comment]
Fixed in https://github.com/Lombiq/Helpful-Extensions/pull/117.
