### ISSUE TITLE
Shape Tracing should skip the PageTitle shape (OSOE-589)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/Helpful-Extensions#120]
This is the shape that goes into the `<title>` HTML element. As far as I've seen the inner HTML of the `<title>` element is treated as plain text in every current browser, so the `<!-- .... -->` is rendered into the beginning of the window title.

![image](https://user-images.githubusercontent.com/4007293/223774254-63938f2f-ce8d-4fb4-8403-8acdd359894d.png)

The shape tracing should make an exception by skipping PageTitle shape for a better developer experience and easier UI testing setup.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-589)

**Comment by Piedone** [comment]
Perhaps rather the shape tracing info needs to be added, but with a different position so it's not part of the `title` tag.

**Comment by 0liver** [comment]
The following error occurred in OSOE-609:

```
error: title text cannot be longer than 70 characters (long-title) at f3d51ba8-d411-469e-8361-55c3415501c2.html:11:42:
   9 | IsCached: False
  10 | --&gt;
> 11 | Blog - Lombiq's OSOCE - UI Testing</title>
     |                                          ^
  12 |     <link type="image/x-icon" rel="shortcut icon" href="/favicon.ico">
  13 |
  14 |     <script src="/Lombiq.BaseTheme/vendors/bootstrap/js/bootstrap.bundle.js?v=SIYbLg8Kyb12W8RgxT7zwNAeUMfrfld1XpKbc_0Q1hE"></script>
Details: https://html-validate.org/rules/long-title.html

1 error found.
```

I don't understand why it doesn't appear for other page tests, but once this is fixed, we need to remove the workaround in _[test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorVueTests.cs](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/448/files/f0c5f1d79c7081f4c5ea56bfbac8a9a9a94ca25a#diff-38b34ea5094639f9326826962a8f262e1c16a130a811b72bfb05c64fbdd04696)_, line 69:

```c#
&& !error.ContainsOrdinalIgnoreCase("title text cannot be longer than 70 characters")
```

**Comment by Piedone** [comment]
In any case, Shape Tracing shouldn't be enabled in a UI test that doesn't actually test Shape Tracing itself.

**Comment by 0liver** [comment]
True.

**Comment by Piedone** [comment]
If the title issue is fixed, Shape Tracing not being enabled in _Lombiq.OSOCE.Tests.recipe.json_ (added in `issue/OSOE-548`) should be evaluated.

**Comment by DemeSzabolcs** [comment]
Do we want to display the shape tracing info of PageTitle? I don't think it's possible to put it elsewhere from [ShapeTracingShapeEvents.cs](https://github.com/Lombiq/Helpful-Extensions/pull/173/files#diff-d6ce973dc0b617a0a60c6f305a8b5cbeaf883aeae4a87319c024938c3979396a).

I think we would need a middleware with additional code, because from `ShapeTracingShapeEvents.cs` we can't "see" outside of the shape. And since this is inside the`<title>`, we can't manipulate the outside. And we can't put comments inside the title.

**Comment by sarahelsaig** [comment]
I still think we don't need it. How about outputting [the text between the comments](https://github.com/Lombiq/Helpful-Extensions/pull/173/files/4fb7710faba349a75460efab54c5d677a801d09f#diff-d6ce973dc0b617a0a60c6f305a8b5cbeaf883aeae4a87319c024938c3979396aR36-R77) as `ILogger.LogInformation()` too? Then it will appear at least somewhere. Also include a note in the docs that TitlePart's comment can't be rendered in the HTML.
