### ISSUE TITLE
Preferred method of including Helpful-Extensions

### ISSUE THREAD

**Issue by devlife** [Lombiq/Helpful-Extensions#16]
I'm curious as to the preferred way of including Helpful-Extensions (and Helpful-Libraries) in an OrchardCore solution? I'd prefer not to use git submodules. Do you have any plans of publishing to NuGet?

**Comment by Piedone** [comment]
At the moment is submodules but we do have plans on pushing our modules to NuGet once Orchard Core 1.0 is out.

**Comment by devlife** [comment]
Thank you.
