### ISSUE TITLE
Menu Widget has stopped working (OSOE-897)

### ISSUE THREAD

**Issue by barthamark** [Lombiq/Helpful-Extensions#175]
Menu Widget doesn't provide the UI to either pick a menu or edit a new one. Probably it stopped working after an Orchard Core upgrade.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-897)

**Comment by sarahelsaig** [comment]
The menu widget processes `INavigationProvider` services where the navigation name is "main" (see [`MainMenuNavigationProviderBase`](https://github.com/Lombiq/Helpful-Libraries/blob/9a3a6f0d087b56113ea5ceb51a7bb2a71b3f4b2a/Lombiq.HelpfulLibraries.OrchardCore/Navigation/MainMenuNavigationProviderBase.cs#L8)) Just like with the admin menus that come from navigation providers, these are added programmatically and can't be edited from the dashboard.

Lombiq.BaseTheme adds a provider called [`MainMenuNavigationProvider`](https://github.com/Lombiq/Orchard-Base-Theme/blob/2bd9952606a2c7bad78b830d9c049d01564c54ba/Lombiq.BaseTheme/Services/MainMenuNavigationProvider.cs) that uses stock OC menu convention. It looks for a content item that has a `MenuItemsListPart` and an alias of "main-menu" so you can edit this content item without the need for a separate UI. If you want to be fancy, you can use OrchardCore.AdminMenu to add a link pointing directly to its content item editor, [OC's Blog recipe](https://github.com/OrchardCMS/OrchardCore/blob/3b3b7f2b6c1ec6d8854a9b2655e0c18da809ea56/src/OrchardCore.Themes/TheBlogTheme/Recipes/blog.recipe.json#L1215) does this for example. (btw we have UI tests for this so we'd know if it was broken)

I don't think there is anything that needs to be done here. Please confirm.

**Comment by barthamark** [comment]
It caused confusion with the client and rightfully so. We should either rename it (e.g., NavigationWidget or MenuPlaceholderWidget) and add description to it where it says what it does exactly. Thoughts?

**Comment by sarahelsaig** [comment]
Renaming would be an unnecessary breaking change with not that much of an improvement in my eyes. I guess we could add further elaboration into the readme and a `.WithDescription()` to the widget's type definition [in the migrations](https://github.com/Lombiq/Helpful-Extensions/blob/975eea127e33516206838bf591b61d91d3b60867/Lombiq.HelpfulExtensions/Extensions/Widgets/Migrations.cs#L48).

**Comment by barthamark** [comment]
How about renaming the Display Name? Also adding Description.

**Comment by sarahelsaig** [comment]
I could go for "Menu Navigation Provider Widget" as display name, if that helps.

**Comment by Piedone** [comment]
So this is only about adding a display name?

**Comment by sarahelsaig** [comment]
Yes, also to add some note in the readme.

**Comment by Piedone** [comment]
OK, thanks. Sounds like an easy issue, then.
