### ISSUE TITLE
Keep the order of items in a search projection

### ISSUE THREAD

**Issue by I3undy** [Lombiq/Helpful-Extensions#2]
@Piedone created on Mar 4, 2014: 
https://helpfulextensions.codeplex.com/workitem/3

To maintain the order of relevance. 
Related: [https://github.com/Lombiq/Helpful-Extensions/issues/1](https://github.com/Lombiq/Helpful-Extensions/issues/1)

**Comment by Piedone** [comment]
We won't do this anymore.
