### ISSUE TITLE
Shape tracing display as title

### ISSUE THREAD

**Issue by timeshift92** [Lombiq/Helpful-Extensions#28]
![image](https://user-images.githubusercontent.com/13614530/120103628-ffaa2680-c169-11eb-8bbf-2b4fc2c90e3c.png)

**Comment by Piedone** [comment]
I don't really know what we could do with this. Fortunately, this is a developer feature that you only enable locally during development :).

**Comment by timeshift92** [comment]
hah understood, thanks for the answer)
