### ISSUE TITLE
How can I add more values for container widget width?

### ISSUE THREAD

**Issue by devlife** [Lombiq/Helpful-Extensions#31]
How can I add/change the values here?

![image](https://user-images.githubusercontent.com/237369/123850107-9c85ee00-d8e7-11eb-9955-fdda4f57a273.png)

**Comment by Piedone** [comment]
You can't but that's not coming from this module. Check out this Orchard issue: https://github.com/OrchardCMS/OrchardCore/issues/6453

**Comment by devlife** [comment]
Yes thank you!
