### ISSUE TITLE
Accordion updates all arrows on click (OSOE-339)

### ISSUE THREAD

**Issue by devlife** [Lombiq/Helpful-Extensions#56]
When clicking a single arrow/header, the correct item is expanded, but the arrows of all of the items are toggled.

![image](https://user-images.githubusercontent.com/237369/156073204-c6ba936b-3fd7-4e7c-a6dd-3771e59f201b.png)

![image](https://user-images.githubusercontent.com/237369/156073222-972ecd64-34ef-4a81-82ad-d220765f9a69.png)

I can take a stab at a fix if you can tell me how to override the cshtml file. I tried `/Views/Shared/BootstrapAccordion.cshtml` and `/Views/Lombiq.HelpfulExtensions/BootstrapAccordion.cshtml` but neither of those worked.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-339)

**Comment by Piedone** [comment]
Thank you! `BootstrapAccordion` is a shape with its shape template, so just _Views/BootstrapAccordion.cshtml_ should work.

**Comment by devlife** [comment]
@Piedone My front end engineer updated the accordion to work with bootstrap 5. Do you want me to push a PR with those changes or just close this issue?

**Comment by Piedone** [comment]
Hmm, it should already work with it, specifically, Bootstrap 5.1.3. But please do and we'll see. (Actually, a Bootstrap reference seems to be missing from the shape.)

**Comment by devlife** [comment]
Ok I'll create a PR for it in the next few days and we can see what you think.

**Comment by Piedone** [comment]
Thanks!

**Comment by Piedone** [comment]
Would you like to circle back to this?

**Comment by Piedone** [comment]
This was previously fixed in https://github.com/Lombiq/Orchard-UIKit/pull/21/files#diff-7a8f5a66f070eea76f90e2b5ec052d8fb67eb4412e074226dd6cc86df6fc9c2f.
