### ISSUE TITLE
Flow 'Additional Styling Part' flyout not activating

### ISSUE THREAD

**Issue by muzzi-w** [Lombiq/Helpful-Extensions#76]
The Flow Additional Styling Part flyout box for adding Custom Classes is not activating on click

![image](https://user-images.githubusercontent.com/12488547/175204817-8b916208-f67d-43e1-840c-f8e4fe42d021.png)

**Comment by Piedone** [comment]
Can you please tell which version of the module and OC you're using?

**Comment by muzzi-w** [comment]
It's module version 4.1.0-alpha.1 (from NuGet) and OC 1.4

**Comment by muzzi-w** [comment]
I probably should try this repo rather than the NuGet version

**Comment by Piedone** [comment]
I see, thanks. This is indeed broken, also in the source. We'll look into it.

**Comment by muzzi-w** [comment]
Possibly related to this and other similar UI/UX instances. https://github.com/OrchardCMS/OrchardCore/issues/11703

**Comment by Piedone** [comment]
Thank you, might indeed be it.

**Comment by Piedone** [comment]
And now it's also up on NuGet.
